// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeetCodeProblems.Migrations.LeetCodeProblems_1148Migrations
{
    [DbContext(typeof(LeetCodeProblems_1148))]
    [Migration("20250908053118_LeetCodeProblems_1148_added_HasNoKey_config")]
    partial class LeetCodeProblems_1148_added_HasNoKey_config
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Views", b =>
                {
                    b.Property<int>("Article_id")
                        .HasColumnType("int");

                    b.Property<int>("Author_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("View_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Viewer_id")
                        .HasColumnType("int");

                    b.ToTable("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
